"""Add dob and anniversary to users

Revision ID: 62746616708a
Revises: 
Create Date: 2026-02-07 18:08:47.905920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '62746616708a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_temples_active'), table_name='temples')
    op.drop_index(op.f('idx_temples_city'), table_name='temples')
    op.drop_index(op.f('idx_temples_deity'), table_name='temples')
    op.drop_table('temples')
    op.alter_column('conversations', 'context',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_index(op.f('idx_conversations_user_id'), table_name='conversations')
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.drop_index(op.f('idx_payments_razorpay_event_id'), table_name='payments')
    op.drop_index(op.f('idx_payments_sankalp_id'), table_name='payments')
    op.create_index(op.f('ix_payments_sankalp_id'), 'payments', ['sankalp_id'], unique=False)
    op.drop_index(op.f('idx_rashiphalalu_date'), table_name='rashiphalalu_cache')
    op.drop_index(op.f('idx_rashiphalalu_rashi'), table_name='rashiphalalu_cache')
    op.create_index(op.f('ix_rashiphalalu_cache_date'), 'rashiphalalu_cache', ['date'], unique=False)
    op.create_index(op.f('ix_rashiphalalu_cache_rashi'), 'rashiphalalu_cache', ['rashi'], unique=False)
    op.alter_column('sankalps', 'razorpay_ref',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index(op.f('idx_sankalps_created_at'), table_name='sankalps')
    op.drop_index(op.f('idx_sankalps_status'), table_name='sankalps')
    op.drop_index(op.f('idx_sankalps_user_id'), table_name='sankalps')
    op.create_index(op.f('ix_sankalps_user_id'), 'sankalps', ['user_id'], unique=False)
    op.drop_constraint(op.f('sankalps_temple_id_fkey'), 'sankalps', type_='foreignkey')
    op.drop_column('sankalps', 'proof_sent_at')
    op.drop_column('sankalps', 'proof_sent')
    op.drop_index(op.f('idx_seva_batches_batch_id'), table_name='seva_batches')
    op.drop_index(op.f('idx_seva_batches_transfer_status'), table_name='seva_batches')
    op.drop_index(op.f('idx_seva_ledger_batch_id'), table_name='seva_ledger')
    op.drop_index(op.f('idx_seva_ledger_created_at'), table_name='seva_ledger')
    op.create_index(op.f('ix_seva_ledger_batch_id'), 'seva_ledger', ['batch_id'], unique=False)
    op.drop_index(op.f('idx_seva_medias_used_count'), table_name='seva_medias')
    op.drop_constraint(op.f('seva_medias_temple_id_fkey'), 'seva_medias', type_='foreignkey')
    op.add_column('users', sa.Column('dob', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('wedding_anniversary', sa.Date(), nullable=True))
    op.alter_column('users', 'rashiphalalu_days_sent',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_index(op.f('idx_users_auspicious_day'), table_name='users')
    op.drop_index(op.f('idx_users_phone'), table_name='users')
    op.drop_index(op.f('idx_users_rashi'), table_name='users')
    op.drop_index(op.f('idx_users_rashiphalalu_days'), table_name='users')
    op.drop_index(op.f('idx_users_state'), table_name='users')
    op.drop_constraint(op.f('users_phone_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.create_unique_constraint(op.f('users_phone_key'), 'users', ['phone'])
    op.create_index(op.f('idx_users_state'), 'users', ['state'], unique=False)
    op.create_index(op.f('idx_users_rashiphalalu_days'), 'users', ['rashiphalalu_days_sent'], unique=False)
    op.create_index(op.f('idx_users_rashi'), 'users', ['rashi'], unique=False)
    op.create_index(op.f('idx_users_phone'), 'users', ['phone'], unique=False)
    op.create_index(op.f('idx_users_auspicious_day'), 'users', ['auspicious_day'], unique=False)
    op.alter_column('users', 'rashiphalalu_days_sent',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_column('users', 'wedding_anniversary')
    op.drop_column('users', 'dob')
    op.create_foreign_key(op.f('seva_medias_temple_id_fkey'), 'seva_medias', 'temples', ['temple_id'], ['id'])
    op.create_index(op.f('idx_seva_medias_used_count'), 'seva_medias', ['used_count'], unique=False)
    op.drop_index(op.f('ix_seva_ledger_batch_id'), table_name='seva_ledger')
    op.create_index(op.f('idx_seva_ledger_created_at'), 'seva_ledger', ['created_at'], unique=False)
    op.create_index(op.f('idx_seva_ledger_batch_id'), 'seva_ledger', ['batch_id'], unique=False)
    op.create_index(op.f('idx_seva_batches_transfer_status'), 'seva_batches', ['transfer_status'], unique=False)
    op.create_index(op.f('idx_seva_batches_batch_id'), 'seva_batches', ['batch_id'], unique=False)
    op.add_column('sankalps', sa.Column('proof_sent', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('sankalps', sa.Column('proof_sent_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('sankalps_temple_id_fkey'), 'sankalps', 'temples', ['temple_id'], ['id'])
    op.drop_index(op.f('ix_sankalps_user_id'), table_name='sankalps')
    op.create_index(op.f('idx_sankalps_user_id'), 'sankalps', ['user_id'], unique=False)
    op.create_index(op.f('idx_sankalps_status'), 'sankalps', ['status'], unique=False)
    op.create_index(op.f('idx_sankalps_created_at'), 'sankalps', ['created_at'], unique=False)
    op.alter_column('sankalps', 'razorpay_ref',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_rashiphalalu_cache_rashi'), table_name='rashiphalalu_cache')
    op.drop_index(op.f('ix_rashiphalalu_cache_date'), table_name='rashiphalalu_cache')
    op.create_index(op.f('idx_rashiphalalu_rashi'), 'rashiphalalu_cache', ['rashi'], unique=False)
    op.create_index(op.f('idx_rashiphalalu_date'), 'rashiphalalu_cache', ['date'], unique=False)
    op.drop_index(op.f('ix_payments_sankalp_id'), table_name='payments')
    op.create_index(op.f('idx_payments_sankalp_id'), 'payments', ['sankalp_id'], unique=False)
    op.create_index(op.f('idx_payments_razorpay_event_id'), 'payments', ['razorpay_event_id'], unique=False)
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.create_index(op.f('idx_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.alter_column('conversations', 'context',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.create_table('temples',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('name_telugu', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(length=100), server_default=sa.text("'Hyderabad'::character varying"), autoincrement=False, nullable=True),
    sa.Column('deity', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('photo_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('google_maps_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('temples_pkey'))
    )
    op.create_index(op.f('idx_temples_deity'), 'temples', ['deity'], unique=False)
    op.create_index(op.f('idx_temples_city'), 'temples', ['city'], unique=False)
    op.create_index(op.f('idx_temples_active'), 'temples', ['is_active'], unique=False)
    # ### end Alembic commands ###
