"""add_message_logs_and_engagement_metrics

Revision ID: dfeaf6951efe
Revises: 5c4910fbcbc0
Create Date: 2026-02-09 10:43:42.154761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfeaf6951efe'
down_revision: Union[str, Sequence[str], None] = '5c4910fbcbc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('message_type', sa.Enum('RASHI', 'NURTURE', 'SANKALP_INVITE', 'ONBOARDING', 'OTHER', name='messagetype'), nullable=False),
    sa.Column('content_preview', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('SENT', 'FAILED', 'DELIVERED', 'READ', name='messagestatus'), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_logs_idempotency_key'), 'message_logs', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_message_logs_user_id'), 'message_logs', ['user_id'], unique=False)
    op.add_column('users', sa.Column('last_engagement_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('streak_days', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('users', sa.Column('lifetime_value', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('users', sa.Column('risk_score', sa.Float(), nullable=False, server_default='0.0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'risk_score')
    op.drop_column('users', 'lifetime_value')
    op.drop_column('users', 'streak_days')
    op.drop_column('users', 'last_engagement_at')
    op.drop_index(op.f('ix_message_logs_user_id'), table_name='message_logs')
    op.drop_index(op.f('ix_message_logs_idempotency_key'), table_name='message_logs')
    op.drop_table('message_logs')
    # ### end Alembic commands ###
